import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

interface FAQProps {
  question: string;
  answer: string;
  value: string;
}

const FAQList: FAQProps[] = [
  {
    question: "What is Tpezz and how does it work?",
    answer:
      "Tpezz is an AI-powered travel itinerary generator. It works by analyzing your preferences, budget, and travel dates to create personalized travel plans. Simply input your details, and Tpezz will generate a custom itinerary for you.",
    value: "item-1",
  },
  {
    question: "Is Tpezz free to use?",
    answer:
      "Tpezz offers a free 'Backpacker' plan with basic features. For more advanced planning tools and support, we offer premium 'Pro' and 'Luxury Explorer' plans at different price points.",
    value: "item-2",
  },
  {
    question: "Can I modify the itinerary generated by Tpezz?",
    answer:
      "Absolutely! While Tpezz provides a great starting point, you have full control to customize your itinerary. You can add, remove, or rearrange activities to suit your preferences.",
    value: "item-3",
  },
  {
    question: "Does Tpezz book  accommodations?",
    answer:
      "Tpezz provides recommendations for accommodations in our 'Pro' and 'Luxury Explorer' plans. While we don't directly book these, we provide links to trusted partners where you can complete your bookings.",
    value: "item-4",
  },
  {
    question: "How far in advance should I plan my trip with Tpezz?",
    answer:
      "We recommend using Tpezz at least 2-3 months before your trip for the best results. This allows time for booking accommodations and activities. However, Tpezz can also create last-minute itineraries if needed.",
    value: "item-5",
  },
];

const FAQ = () => {
  return (
    <section id="Faqs" className="container pt-24 sm:pt-32">
      <h2 className="text-3xl md:text-4xl font-bold mb-4">
        Frequently Asked{" "}
        <span className="bg-gradient-to-b from-primary/60 to-primary text-transparent bg-clip-text">
          Questions
        </span>
      </h2>

      <Accordion type="single" collapsible className="w-full AccordionRoot">
        {FAQList.map(({ question, answer, value }: FAQProps) => (
          <AccordionItem key={value} value={value}>
            <AccordionTrigger className="text-left">
              {question}
            </AccordionTrigger>

            <AccordionContent>{answer}</AccordionContent>
          </AccordionItem>
        ))}
      </Accordion>

      <h3 className="font-medium mt-4">
        Still have questions?{" "}
        <a
          href="#contact"
          className="text-primary border-primary border-b-2 hover:border-0"
        >
          Contact our travel experts
        </a>
      </h3>
    </section>
  );
};

export default FAQ;
